#!/bin/sh -x
# $Id: mk,v 1.1 2018-05-24 10:39:07-07 - - $
cid + $0 haversine.perl
cmd="haversine.perl lax sfo sjc nyc sfo sea"
(echo COMMAND: $cmd; echo ''; $cmd) >haversine.output
mkpspdf haversine.lis.ps haversine.perl haversine.output
mkpspdf database.pl.ps .score/database.pl
